import { StyleSheet } from "react-native";
import { colors } from "../../styles/colors";
import { fontSize, radius, spacing } from "../../styles/theme";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: "transparent",
    justifyContent: "center",
    padding: spacing.sm,
  },
  pageTitle: {
    fontSize: fontSize.xl,
    color: colors.black,
    fontWeight: "bold",
    paddingLeft: spacing.sm,
    paddingVertical: spacing.sm,
  },
  searchbar: {
    borderColor: colors.black,
    borderWidth: 1,
    borderRadius: radius.sm,
    width: "100%",
    padding: spacing.sm,
    marginVertical: spacing.sm,
    marginHorizontal: "auto",
    backgroundColor: colors.white,
    alignItems: "center",
  },
  subTitle: {
    fontSize: fontSize.xl,
    fontWeight: "600",
    alignItems: "flex-start",
    width: "100%",
    paddingVertical: spacing.sm,
    paddingLeft: spacing.sm,
  },
  backgroundImage: {
    borderRadius: spacing.sm,
  },
  artistImages: {
    width: "100%",
    height: 100,
    borderColor: colors.black,
    borderWidth: 1,
  },
  recommendFactor: {
    width: "100%",
    shadowColor: colors.black,
    shadowOffset: { width: 1, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
  },
  recommendContainer: {
    width: "100%",
    alignItems: "center",
    display: "flex",
    flexDirection: "row",
    height: "auto",
    marginBottom: spacing.sm,
    backgroundColor: "transparent",
  },
  recommendList: {
    paddingVertical: spacing.xs,
  },
  dotsContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: spacing.xs,
    width: "100%",
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: "100%",
    backgroundColor: colors.lightGray,
    marginHorizontal: spacing.xs,
  },
  activeDot: {
    width: 10,
    height: 10,
    borderRadius: "100%",
    backgroundColor: colors.black,
  },
  recentContainer: {
    width: "100%",
    alignItems: "center",
    flexWrap: "wrap",
    flex: 1,
    height: "auto",
    marginBottom: spacing.sm,
  },
  recentContents: {
    width: "95%",
    height: "auto",
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "spce-between",
  },
  recentImagesS: {
    width: "50%",
    height: 200,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: radius.sm,
    backgroundColor: colors.white,
    margin: spacing.xs,
  },
  recentImagesL: {
    width: "40%",
    height: 200,
    justifyContent: "center",
    alignItems: "center",
    margin: spacing.xs,
    borderRadius: radius.sm,
    backgroundColor: colors.white,
  },
  recentPlaceholder: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: radius.sm,
    borderColor: "transparent",
    borderWidth: 1,
  },
  iconButton: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
    alignItems: "center",
    justifyContent: "center",
    borderColor: colors.gray,
    borderWidth: 1,
    borderRadius: radius.md,
  },
  disabledIcon: {
    opacity: 0.35,
  },
  buttonContainer: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: spacing.sm,
    paddingRight: spacing.sm,
    marginTop: spacing.sm,
  },
  imageBackground: {
    width: "100%",
    height: 200,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: spacing.sm,
  },
  endedImages: {
    width: 130,
    height: 90,
  },
  endedContentsContainer: {
    width: "95%",
    alignItems: "center",
    flexDirection: "row",
    height: "auto",
    display: "flex",
    marginVertical: spacing.sm,
    justifyContent: "center",
  },
  endedContents: {
    width: "55%",
    flexDirection: "column",
    height: "auto",
    display: "flex",
    marginVertical: spacing.xs,
    marginLeft: spacing.xs,
  },
  endedNamecStyle: {
    marginVertical: spacing.xs,
    marginHorizontal: spacing.xs,
    width: "90%",
    color: colors.black,
    fontSize: fontSize.sm,
    flexWrap: "wrap",
    display: "flex",
    fontWeight: "bold",
  },
  endedContainer: {
    width: "100%",
    alignItems: "center",
    flexDirection: "column",
    height: "auto",
    marginBottom: spacing.sm,
  },
  artInPlaceContainer: {
    width: "100%",
    alignItems: "center",
    flexDirection: "column",
    backgroundColor: colors.lightGray50,
    height: "auto",
    marginTop: spacing.xl,
  },
  artInPlaceContents: {
    width: "100%",
    paddingHorizontal: spacing.xl,
    paddingBottom: spacing.xl,
  },
  artInimageBackground: {
    width: "100%",
    height: 100,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: spacing.sm,
    borderColor: "transparent",
    borderWidth: 1,
    borderRadius: radius.sm,
  },
  artInbackgroundImage: {
    borderRadius: radius.sm,
    width: 100,
    height: 120,
    marginVertical: spacing.sm,
  },
  userRecommendContainer: {
    width: "90%",
    marginBottom: spacing.xl,
    marginHorizontal: "auto",
  },

  userCard: {
    width: 110,
    marginRight: spacing.md,
    alignItems: "center",
    backgroundColor: colors.white,
    borderRadius: radius.sm,
    padding: spacing.sm,
    shadowColor: colors.black,
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },

  userAvatar: {
    width: 60,
    height: 60,
    borderRadius: radius.lg,
    backgroundColor: colors.lightGray,
    marginBottom: spacing.xs,
    overflow: "hidden",
  },

  userName: {
    fontWeight: "bold",
    fontSize: fontSize.sm,
  },

  userDesc: {
    fontSize: fontSize.xs,
    color: colors.gray,
    marginBottom: spacing.xs,
  },
  followBtn: {
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: radius.xs,
    marginTop: spacing.sm,
    height: 20,
  },
});
