import { Dimensions, StyleSheet } from "react-native";
import { colors } from "../../styles/colors";
import { fontSize, radius, spacing } from "../../styles/theme";

const { width } = Dimensions.get("window");
const styles = StyleSheet.create({
  searchbar: {
    borderColor: colors.black,
    borderWidth: 1,
    borderRadius: radius.sm,
    width: "100%",
    padding: spacing.sm,
    marginHorizontal: "auto",
    marginVertical: spacing.lg,
    backgroundColor: colors.white,
    alignItems: "center",
  },
  topFactorContainer: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    padding: spacing.sm,
    alignItems: "center",
    margin: "auto",
  },
  pageTitle: {
    fontSize: fontSize.xl,
    color: colors.black,
    fontWeight: "bold",
  },
  filterContianer: {
    width: "45%",
    marginLeft: spacing.xs,
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  filterFactor: {
    marginRight: spacing.sm,
    fontSize: fontSize.sm,
    color: colors.black,
    fontWeight: "600",
  },
  reviewsContainer: {
    width: "95%",
    borderWidth: 1,
    borderRadius: radius.sm,
    borderColor: colors.primary,
    padding: spacing.xl,
    marginTop: spacing.xl,
    margin: "auto",
  },
  reviewFactor: {
    marginBottom: 50,
    width: "100%",
    flexDirection: "column",
  },
  reviewTumblnail: {
    width: width * 0.9,
    height: 270,
  },
  ProfileTumbnail: {
    width: 40,
    height: 40,
    marginRight: spacing.lg,
    borderRadius: 100,
  },
  ProfileImage: {
    borderRadius: 100,
    borderColor: colors.primary,
    borderWidth: 1,
  },
  profileContainer: {
    width: "85%",
    height: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    padding: spacing.sm,
  },
  reviewTextContainer: {
    padding: spacing.sm,
  },
  reviewDescStyle: {
    fontSize: fontSize.sm,
    color: colors.gray300,
    marginVertical: spacing.xs,
    lineHeight: spacing.xl,
  },
  reactionContainer: {
    width: "95%",
    flexDirection: "row",
    justifyContent: "flex-start",
    padding: spacing.sm,
    borderTopColor: colors.black,
    borderTopWidth: 1,
    margin: "auto",
  },
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 200,
  },
  overlayContent: {
    padding: spacing.xl,
    borderRadius: spacing.xs,
    backgroundColor: "rgba(0,0,0,0.6)",
    alignItems: "center",
  },
  ReviewBtn: {
    position: "absolute",
    zIndex: 999,
    bottom: spacing.xl,
    right: spacing.xl,
    borderRadius: 100,
    alignItems: "center",
    width: 56,
    height: 56,
    pointerEvents: "box-none",
  },
  ReviewBtnInner: {
    width: "90%",
    height: "90%",
    borderRadius: 100,
    position: "absolute",
    alignItems: "center",
    backgroundColor: colors.primary,
  },
  ReviewBtnText: { margin: "auto", fontSize: fontSize.xxl },
  indicatorContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: spacing.xs,
  },

  indicator: {
    width: 6,
    height: 6,
    borderRadius: 100,
    backgroundColor: colors.lightGray,
    marginHorizontal: spacing.xs,
  },

  activeIndicator: {
    backgroundColor: colors.black,
  },
  followBtn: {
    marginLeft: spacing.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: radius.xs,
    backgroundColor: colors.primary,
  },
  unfollowBtn: {
    marginLeft: spacing.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: radius.xs,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  followBtnText: {
    color: colors.white,
    fontWeight: "bold",
    fontSize: fontSize.xs,
  },
  unfollowBtnText: {
    color: colors.primary,
    fontWeight: "bold",
    fontSize: fontSize.xs,
  },
});
